spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/deeplearning?serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=root
spring.datasource.password=1208
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

jwt.secret=jwtpassword123jwtpassword123jwtpassword123jwtpassword123jwtpassword
jwt.expiration=3600000

# Oracle Cloud Object Storage ??
oracle.config.compartment-ocid=ocid1.bucket.oc1.ap-chuncheon-1.aaaaaaaaodrjy2nnqjcv64yqex2bo3avgt3366a5aak2rxv6nxuc4g25qpxa
oracle.config.region=ap-chuncheon-1
oracle.config.bucket-name=ar-filter-images
oracle.config.namespace=axsd9z3medjm
